### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by brachy84** [CleanroomMC/GroovyScript#120]
- [ ] Docs PR + Doc all existing compat (TiC !)
- [ ] Full Gamestages support
- [ ] Material system like contentweaker (maybe steal gregtech)

## High Priority mod support (reload)
- [ ] TFC
- [ ] GregTech Multiblocks / Singleblock helpers
- [ ] Nuclearcraft ???
- [x] Thermalexpansion

**Comment by Wizzerinus** [comment]
Docs needed from currently-implemented compats:
- Forestry (lack of subpages)
- IC2C (entirely missing)
- IC2Exp (entirely missing)

I will likely add these since I need them to test the input quantity PR.

Compats that are added externally:
- GTCEu
- MekCEu
- NC:O

If I had a say in this I would not host GTCEu docs on the GrS website since it will likely become outdated, although that's the case for the GrS-native ones too, so idk
